services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: backend/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5200:80"
    depends_on:
      - db
      - identity
  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1234sdu
      - POSTGRES_DB=shop
    ports:
      - "5432:5432"

  identity:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1234sdu
      - POSTGRES_DB=identity
    ports:
      - "5433:5432"
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"